[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/logs

[BitTorrent]
Session\AddTorrentStopped=false
Session\DefaultSavePath=/data/downloads/complete
Session\ExcludedFileNames=
Session\GlobalMaxRatio=-1
Session\GlobalMaxSeedingMinutes=10
Session\Port=3994
Session\QueueingSystemEnabled=true
Session\SSL\Port=16222
Session\ShareLimitAction=Stop
Session\TempPath=/data/downloads/incomplete
Session\TempPathEnabled=true

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Cookies=@Invalid()
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
General\Locale=en
MailNotification\req_auth=true
WebUI\CSRFProtection=false
WebUI\HostHeaderValidation=false
WebUI\Password_PBKDF2="@ByteArray(Y1nMjsUZv94gyA54pwgL5Q==:WQ8VUCeiadRLymewStXeiZ70/NCOKoFvkhyjPUT1vIqvFp6YObXpmHDu3Xn4h6LJlVNAB+OE9XmkjOisKUHRkw==)"
WebUI\Port=8080

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
