[global]
   workgroup = WORKGROUP
   server string = HomeLab Samba Server
   map to guest = Bad User
   log file = /var/log/samba/log.%m
   max log size = 1000
   server role = standalone server
   obey pam restrictions = yes
   unix password sync = yes
   passwd program = /usr/bin/passwd %u
   passwd chat = *Enter\snew\s*password:* %n\n *Retype\snew\s*password:* %n\n *password\supdated\ssuccessfully* .
   pam password change = yes
   usershare allow guests = yes

[media]
   path = /storage
   browseable = yes
   read only = no
   guest ok = no
   create mask = 0664
   directory mask = 0775
